# Generated by Django 3.2.1 on 2021-05-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brandId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('brandURL', models.URLField()),
                ('description', models.CharField(max_length=255)),
                ('brandEmail', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
