# Generated by Django 3.2.1 on 2021-05-07 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210507_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brandEmail',
            field=models.CharField(default='', max_length=60),
        )
    ]
