# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=255)),
                ('roleId', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('dtm_crt', models.DateTimeField()),
                ('verified_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
