# Generated by Django 2.0 on 2021-05-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_musicstoredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
