# Generated by Django 2.0 on 2021-04-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_user_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicStoreData',
            fields=[
                ('musicStoreDataID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.BigIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('musicStorePicture', models.ImageField(upload_to='')),
            ],
        ),
    ]
