# Generated by Django 3.2.1 on 2021-05-04 14:14

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('subCategoryId', models.BigIntegerField()),
                ('brandId', models.BigIntegerField()),
                ('productName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('videoUrl', embed_video.fields.EmbedVideoField()),
                ('minPrice', models.BigIntegerField()),
                ('maxPrice', models.BigIntegerField()),
                ('dtm_crt', models.DateTimeField()),
            ],
        ),
    ]
